server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    password: auth123
    username: auth
  jpa:
     hibernate:
      ddl-auto: create
     properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
     show-sql: true
